### ISSUE TITLE
Can we minify our docker image?

### ISSUE THREAD

**Issue by bddenhartog** [bddenhartog/docker-murmur#56]
Right now, we have a pretty lightweight image based off of `alpine`. We can further optimize by grabbing the static binary and basing this image off of `scratch` or `busybox`.

Some thinking will need to go into how we want to handle configuration with this, as `sed` won't exist in `scratch`. I'm not a fan of lugging around a `murmur.ini` in the repository, as it can change between versions. Maybe this is a blocking point for this task, maybe not. Thoughts @SISheogorath?

**Comment by SISheogorath** [comment]
I wouldn't do it. Because as you mentioned yourself we will loose `sed` and also loose some useful tools for debugging in case we build from `scratch`. 

For further improvement we can use the currently marked as experimental `--squash` flag on build. that would *maybe* remove a few bytes. But right now I don't see any reason for further minification without using a lot of useful tooling inside the container.

Maybe we should simply open an issue in murmur and ask for configuration based on environment variables. In case they fix that I would completely support your idea with building it from scratch.

**Comment by bddenhartog** [comment]
> Maybe we should simply open an issue in murmur and ask for configuration based on environment variables

That's a good idea. I've done that here: mumble-voip/mumble#2782

**Comment by bddenhartog** [comment]
Closing until further development in mumble-voip/mumble#2782.
